[[functions]]
address = 0x824625F0
name = "fn_824625F0_manual"

[[functions]]
address = 0x82462A00
name = "fn_82462A00_manual"

[[functions]]
address = 0x825C50A8
name = "fn_825C50A8_manual"

[[functions]]
address = 0x825E7B78
name = "fn_825E7B78_manual"

[[functions]]
address = 0x825D0840
name = "fn_825D0840_manual"